// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAF7V23l2Gq_YSTqpko25hr4TvVyYjMJc',
    appId: '1:956190303057:web:38b63ec50cf51efa22e970',
    messagingSenderId: '956190303057',
    projectId: 'firebase-training-app',
    authDomain: 'fir-training-app-32cbf.firebaseapp.com',
    storageBucket: 'firebase-training-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAj0iDc8FwvS5lKtLqNwVHkc9DcXMS7f0',
    appId: '1:956190303057:android:a75cebcf8ff780fd22e970',
    messagingSenderId: '956190303057',
    projectId: 'firebase-training-app',
    storageBucket: 'firebase-training-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPrTLcAy1NsTFCOqz4U4u1Qi2L-Tmw9s4',
    appId: '1:956190303057:ios:47fd4505575d374022e970',
    messagingSenderId: '956190303057',
    projectId: 'firebase-training-app',
    storageBucket: 'firebase-training-app.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTraining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPrTLcAy1NsTFCOqz4U4u1Qi2L-Tmw9s4',
    appId: '1:956190303057:ios:47fd4505575d374022e970',
    messagingSenderId: '956190303057',
    projectId: 'firebase-training-app',
    storageBucket: 'firebase-training-app.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTraining',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAF7V23l2Gq_YSTqpko25hr4TvVyYjMJc',
    appId: '1:956190303057:web:dfc08610e90424f022e970',
    messagingSenderId: '956190303057',
    projectId: 'firebase-training-app',
    authDomain: 'fir-training-app-32cbf.firebaseapp.com',
    storageBucket: 'firebase-training-app.firebasestorage.app',
  );
}
